### ISSUE TITLE
Set up the project with a proper structure, including necessary configuration files and initial setup.

### ISSUE THREAD

**Issue by akanksha2305** [upes-open/OSoC-24-descr.ai.be#1]
Tasks:
1. Initialize a new Node.js project.
2. Set up Webpack for bundling.
3. Create manifest.json for the Chrome extension.

**Comment by sakshammaggu** [comment]
Hi, I would like to take up this issue

**Comment by akanksha2305** [comment]
@sakshammaggu assigned.

**Comment by sakshammaggu** [comment]
Hi, I have made a PR.

**Comment by akanksha2305** [comment]
@sakshammaggu we will review the PR and let u know soon.

**Comment by Archisha-Dhyani** [comment]
i would like to work on this issue.
