### ISSUE TITLE
Develop a custom AI model for generating summaries of bookmarked content.

### ISSUE THREAD

**Issue by akanksha2305** [upes-open/OSoC-24-descr.ai.be#15]
Tasks:
1. Train a custom model for summarization.
2. Deploy the model to a server or cloud platform.
3.

**Comment by Archisha-Dhyani** [comment]
i would like to work on this issue.

**Comment by akanksha2305** [comment]
@Archisha-Dhyani assigned

**Comment by rampantvoid** [comment]
@akanksha2305 hi can i work on this?

**Comment by akanksha2305** [comment]
@rampantvoid assigned
