### ISSUE TITLE
Develop a custom AI model to classify bookmarks with tags.

### ISSUE THREAD

**Issue by akanksha2305** [upes-open/OSoC-24-descr.ai.be#16]
Tasks:
1. Train a custom model for tag classification.
2. Deploy the model to a server or cloud platform.

**Comment by XD-coder** [comment]
cant we use pre trained models via api , as they will be much more accurate and efficient

**Comment by akanksha2305** [comment]
@XD-coder it is better but we want the project to be made from the scratch without using pre-made things.

**Comment by rampantvoid** [comment]
@akanksha2305 hi, can you assign this to me

**Comment by akanksha2305** [comment]
@rampantvoid assigned
