### ISSUE TITLE
 Integrate the custom summary model with the Chrome extension to generate summaries.

### ISSUE THREAD

**Issue by akanksha2305** [upes-open/OSoC-24-descr.ai.be#17]
Tasks:
1. Set up an API endpoint for the summary model.
2. Fetch summaries from the model via API calls in the extension.

**Comment by raghvendragoyal01** [comment]
Hello mam pls gave me this task.

**Comment by akanksha2305** [comment]
@raghvendragoyal01 assigned.

**Comment by rampantvoid** [comment]
@akanksha2305 hey, can i be assigned to this issue

**Comment by akanksha2305** [comment]
@rampantvoid done
