### ISSUE TITLE
Create a logo for this project!

### ISSUE THREAD

**Issue by akanksha2305** [upes-open/OSoC-24-descr.ai.be#28]
I want a logo for our project "descr.ai.be" which can be used on the extension and it's dashboard.

**Comment by XD-coder** [comment]
Should I post a few logo here in comments setself ?

**Comment by akanksha2305** [comment]
@XD-coder first, get the issue assigned and then you can create a folder called "icons" and add your logo there.

**Comment by akanksha2305** [comment]
@XD-coder should i assign the issue to you?

**Comment by XD-coder** [comment]
@akanksha2305 I have multiple logos ready do go. Maybe we can decide which one to choose first ???

**Comment by XD-coder** [comment]
I can share them on discord or just send them all here (I have 9 designs)

**Comment by akanksha2305** [comment]
@XD-coder share them on discord !

**Comment by NavySaw23** [comment]
@XD-coder you have been assigned this issue

**Comment by XD-coder** [comment]
@NavySaw23  @akanksha2305  sent a PR
