### ISSUE TITLE
Design the user interface for the bookmarks page

### ISSUE THREAD

**Issue by akanksha2305** [upes-open/OSoC-24-descr.ai.be#3]
Tasks:
Design a UI design for a page accessible from the extension that displays all bookmarks with search and sorting functionality and also design the authentication page. 

You can do this using Figma or any other tool for UI designing you see fit.

**Comment by rishabh-108272** [comment]
I would like to work in this issue.

**Comment by rishabh-108272** [comment]
I would like to work in this issue.

**Comment by akanksha2305** [comment]
@rishabh-108272 assigned!

**Comment by rampantvoid** [comment]
@akanksha2305 can you assign this to me
