### ISSUE TITLE
 Implement the user interface for the extension

### ISSUE THREAD

**Issue by akanksha2305** [upes-open/OSoC-24-descr.ai.be#4]
Task: 
Implement the user interface for the extension using html, css. Issue no. 2 has the issue of designing the UI for the extension. Incase, it is not done and you design the extension, you will get points for both issues.

**Comment by rishabh-108272** [comment]
I would like to work in this issue.

**Comment by akanksha2305** [comment]
@rishabh-108272 assigned , also join our discord channels for smooth communications!

**Comment by Archisha-Dhyani** [comment]
i would like to work on this issue

**Comment by akanksha2305** [comment]
@Archisha-Dhyani assigned !

**Comment by shradiphylleia** [comment]
would like to work.pls assign

**Comment by rampantvoid** [comment]
hi can i be assigned on this issue
