### ISSUE TITLE
Implement the user interface of the bookmark page

### ISSUE THREAD

**Issue by akanksha2305** [upes-open/OSoC-24-descr.ai.be#5]
Implement the user interface for the bookmark page using html, css. Issue no. 3 has the issue of designing the bookmark and authentication page. Incase, it is not done and you design the extension, you will get points for both issues.

**Comment by rishabh-108272** [comment]
Hi, I would like to work in this issue.

**Comment by akanksha2305** [comment]
@rishabh-108272 assigned

**Comment by iDream2** [comment]
Hi, i would like to work on this issue. Can this be assigned to me,as well ?

**Comment by akanksha2305** [comment]
@iDream2 sure assigned. 
@rishabh-108272 whoever first commits, will get the points.

**Comment by rishabh-108272** [comment]
PR created. Please review once.

**Comment by akanksha2305** [comment]
@shradiphylleia assigned. yes it refers to implementation of user bookmarks with login/signup pages. 
@rishabh-108272 @iDream2 all of you please keep in mind, whoever completes this issue first will be given the points.

**Comment by akanksha2305** [comment]
@shradiphylleia @rishabh-108272 @iDream2 i have changed the issue to only creating the dashboard for the bookmark extension so that we can access our bookmarks.

**Comment by shradiphylleia** [comment]
the login and signup page issue has been put on hold or is part of some other issue.

**Comment by akanksha2305** [comment]
@shradiphylleia part of some other issue

**Comment by shradiphylleia** [comment]
> @shradiphylleia part of some other issue

was unable to find the same pls let me know the issue number as i was half way done with login/sign up.will link the mockup there.

**Comment by akanksha2305** [comment]
@shradiphylleia @rishabh-108272 @iDream2 guys check out the authentication pages done, please follow that design so that we can have some uniformity.
