### ISSUE TITLE
Add Context Menu for Bookmarking Elements

### ISSUE THREAD

**Issue by akanksha2305** [upes-open/OSoC-24-descr.ai.be#6]
Modify the context menu to allow users to bookmark a specific paragraph or element on a page.

Tasks:
1. Add a context menu item for bookmarking.
2. Implement logic to capture and save selected text or elements.
3. Tech Stack: Chrome Extensions API, JavaScript

**Comment by Lavanya-glitch** [comment]
i want to work on this

**Comment by akanksha2305** [comment]
@Lavanya-glitch assigned. incase of any  queries, kindly ping me or navinya on discord

**Comment by Saga690** [comment]
Would like to work on this!
