### ISSUE TITLE
 Set up a cloud-based database to store bookmarks, summaries, keywords, and notes.

### ISSUE THREAD

**Issue by akanksha2305** [upes-open/OSoC-24-descr.ai.be#7]
Tasks:
1. Initialize Firebase project and Firestore.
2. Configure Firebase in the extension.
3. Implement basic CRUD operations for bookmarks.
4. Tech Stack: Firebase Firestore, Firebase SDK, Node.js

The database will be provided to you by the repository maintainer, kindly ask them for access before doing the work.

**Comment by rampantvoid** [comment]
@akanksha2305 hey, if it's still open i would like to work on this

**Comment by akanksha2305** [comment]
@rampantvoid assigned
