### ISSUE TITLE
Implement authentication page user interface

### ISSUE THREAD

**Issue by akanksha2305** [upes-open/OSoC-24-descr.ai.be#8]
Implement the user interface for the authentication page using html, css. Issue no. 3 has the issue of designing the authentication page. Incase, it is not done and you design the ui, you will get points for both issues.

**Comment by nandiniiiiiiii** [comment]
Hello ma'am I would like to work on this. kindly assign this to me.

**Comment by akanksha2305** [comment]
@nandiniiiiiiii assigned. kindly join the discord channels for smooth communication.

**Comment by nandiniiiiiiii** [comment]
So, this auth page will be like a login/signup page right or do I have to add other functions as well...??

**Comment by akanksha2305** [comment]
@nandiniiiiiiii yes it will be the login/signup pages

**Comment by shradiphylleia** [comment]
would like to work on this issue.

**Comment by rampantvoid** [comment]
@akanksha2305 hi can you assign this to me
