### ISSUE TITLE
Implement User Authentication

### ISSUE THREAD

**Issue by akanksha2305** [upes-open/OSoC-24-descr.ai.be#9]
Tasks:
1. Set up Firebase Authentication.
2. Implement Google sign-in.
3. Manage user sessions and store user-specific data.

Tech Stack: Firebase, JavaScript

**Comment by shradiphylleia** [comment]
i would like to take this up.will need a days or two to resolve this.

**Comment by adx04** [comment]
hello there Akansha! i would like to work on this issue

**Comment by akanksha2305** [comment]
@shradiphylleia @adx04 both of you are assigned. whoever resolves it first, will receive the points.

**Comment by adx04** [comment]
@akanksha2305 , how should the folder structure be like (any suggestions or things you want to particularly mention so there i won't be missing anything)

**Comment by akanksha2305** [comment]
@adx04 for now make an auth folder and implement in that

**Comment by adx04** [comment]
@akanksha2305 ok like a folder with my name and respective files inside it?

**Comment by rampantvoid** [comment]
@akanksha2305 hi, i would like to work on it
